on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  trigger_jenkins_pipeline:
    if: github.event.pull_request.merged == true
    name: trigger jenkins pipeline
    runs-on: ubuntu-latest
    steps:
    - name: jenkins job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{secrets.JENKINS_TRIGGER_URL}}
        user: "admin"
        token: ${{secrets.TRIGGER_API_TOKEN}}
        job: "test-pipeline"
        
    
